TIPS = [
  ['Keyboard versus Mouse', 'Learn your shortcuts! Using the mouse (or trackpad) slows you down.'],
  ['Restart faster', 'You can restart an exercise fast by using the excape key!'],
  ['Shift versus CapsLock', 'You should almost never use CapsLock. Shift is best.'],
  ['Home row', 'Left hand on a, s, d and f; right hand on j, k, l, and ;.'],
  ['Returning home', 'Bring your fingers back to the home row to type faster.'],
  ['Touchtyping', 'You are learning how to touchtype! This is the fasted way to type.'],
  ['Touch your fingers', 'The closer you keep you fingers to the keys, the faster you will be.'],
  ['Eyes on the ball', 'If you know where the keys are, you do not have to look. Keep your eyes on your work, not on your tools.'],
  ['Lesson shortcut', 'When you complete an exercise, you can jump to the next lesson faster by using the enter key.'],
  ['Know your rank', 'Find the rankings section at the top of the homepage, you may be the fastest typist you know!'],
  ['Rest between practice', 'You do not need to race on to the next exercise today. Come back tomorrow for a fresh start.'],
  ['Alternating shift keys', 'Use whichever shift key is opposite the key you are augmenting.'],
  ['Exercises are unique', 'Every exercise has different goals.'],
  ['Achievements', 'Come back to lessons later when you are more accurate or faster.'],
  ['Posture', 'To type faster, sit with your back straight and feet on the floor.'],
  ['Relax', 'The words per minute timer does not start until you start typing.'],
  ['Review', 'Take some time to visit the home page and review your progress.'],
]