module QWERTY
  LESSONS = [
    ['Home Row Position',
     [['jkkjk kjkkj jkjjk kkjkj jjkjk jkjkk kjkjj jkjkj kkjkj jjkjk',          'j and k',               2, 15, 35],
      ['dffdf fdffd dfddf ffdfd ddfdf dfdff fdfdd dfdfd ffdfd ddfdf',          'd and f',               2, 15, 35],
      ['dkfdj jdfkf kjdkf fkjdk fkdkj fkfdj kjdkf dfkfj kfkdj fjkjd',          'j, k, d and f',         2, 15, 35],
      ['l;;l; ;l;;l l;ll; ;;l;l ll;l; l;l;; ;l;ll l;l;l ;;l;l ll;l;',          'l and ;',               2, 15, 35],
      ['lfk ;fk djlf kflf ;fkj kj;f dj;;f ;f;lf ;lfkf dljdf ;f;lfkf',          'First review',          2, 15, 35],
      ['assas sassa asaas ssasa aasas asass sasaa asasa ssasa aasas',          'a and s',               2, 15, 35],
      ['all add; as ask; sad; fas lad dak; dad fad fall; lass dall;',          'Second review',         2, 15, 35],
      ['alas dald fall; dad flak; lass sad; fass; all fall lad; ask',          'Home challenge',        2, 15, 35]]],

    ['Index Fingers 1',
     [['ghhgh hghhg ghggh hhghg gghgh ghghh hghgg ghghg hhghg gghgh',          'g and h',               2, 15, 35],
      ['gad has aha; had flag gas; sag ash; gag dash glag half;',              'Home row final',        2, 15, 35],
      ['tfftf fttft tftff ftftt tftft ftftf ffttf ttfft tft ftf',              't and back',            2, 15, 35],
      ['tft tsk alt gst has hat kat sha ska tad tag that tas tsk',             'Review with t',         2, 15, 35],
      ['rffrf frrfr rfrff frfrr rfrfr frfrf ffrrf rrffr rfr frf',              'r and back',            2, 15, 35],
      ['rag ark rash jarl trash; rash rad lard; drag lar jar',                 'Review with r',         2, 15, 35],
      ['raft; draft arts gats trad task shard hard; hath halt gast',           'Left pointer',          2, 15, 35],
      ['yjjyj jyyjy yjyjj jyjyy yjyjy jyjyj jjyyj yyjjy yjy jyj',              'From y to j',           2, 15, 35],
      ['ya yald gay yak; yard sty fly kays day kyaf slay; yald lys',           'Review with y',         2, 15, 35],
      ['ujjuj juuju ujujj jujuu ujuju jujuj jjuuj uujju uju juj',              'From u to j',           2, 15, 35],
      ['uh husk tau sku; ludd yuk ugh uru juku us; guff usla dull',            'Right pointer',         2, 15, 35],
      ['yurt lady try tardy stray; stalk ya lathy; flay rhytha',               'Midterm review',        2, 15, 35]]],

    ['Index Fingers 2',
     [['vffvf fvvfv vfvff fvfvv vfvfv fvfvf ffvvf vvffv vfv fvf',              'From v to f',           2, 15, 35],
      ['varus vasty lav var; sylva vat guv; davy vulgar ulvas',                'Review with v',         2, 15, 35],
      ['bjjbj jbbjb bjbjj jbjbb bjbjb jbjbj jjbbj bbjjb bjb jbj',              'From b to f',           2, 15, 35],
      ['bad labs dab bald albs; tabs flab bard jab; grub buys garb',           'Review with b',         2, 15, 35],
      ['njjnj jnnjn njnjj jnjnn njnjn jnjnj jjnnj nnjjn njn jnj',              'From n to j',           2, 15, 35],
      ['nag and fang; dank hang hank nah; flank land sangh khan',              'Review with n',         2, 15, 35],
      ['the rags rang vast; bag lard jant ban yards; stud turk',               'Upper review',          2, 15, 35],
      ['mjjmj jmmjm mjmjj jmjmm mjmjm jmjmj jjmmj mmjjm mjm jmj',              'From m to j',           2, 15, 35],
      ['mum mut sham rams slam; slum gama smut balm arm mans flam',            'Review with m',         2, 15, 35],
      ['mad marts smart human; numb ban nag ma and mass lamb rut',             'Lower review',          2, 15, 35],
      ['vans tan rash fangs; balm must slam sand; arms man salt',              'Index challenge',       2, 15, 35]]],

    ['Middle and Ring Fingers 1',
     [['edded deede ededd dedee edede deded ddeed eedde ede ded',              'From d to e',           2, 15, 35],
      ['dead ed eats eels; the deal dreads to trend; red age fed',             'Review with e',         2, 15, 35],
      ['vane envy ends vets vent; use menu but let ten stay fed',              'Left side',             2, 15, 35],
      ['wssws swwsw wswss swsww wswsw swsws sswws wwssw wsw sws',              'From s to w',           2, 15, 35],
      ['sway jaws swat the swan; news was swell when laws saw newt',           'Review with w',         2, 15, 35],
      ['ikkik kiiki ikikk kikii ikiki kikik kkiik iikki iki kik',              'From k to i',           2, 15, 35],
      ['kids like kin; kiln kits hike; kale shakes skate unkind',              'Review with i',         2, 15, 35],
      ['skew vader with likes; liken jade at envy drew swung',                 'Right side',            2, 15, 35],
      ['ollol loolo ololl loloo ololo lolol llool oollo olo lol',              'From l to o',           2, 15, 35],
      ['old lords sold bold lots; lads of lore glob local glue',               'Review with o',         2, 15, 35],
      ['glow alone or redo ideas; sweat on the show for one halo',             'Midterm review',        2, 15, 35]]],

    ['Middle and Ring Fingers 2',
     [['cddcd dccdc cdcdd dcdcc cdcdc dcdcd ddccd ccddc cdc dcd',              'From d to c',           2, 15, 35],
      ['act coy card aced dice can tacs duct ice ache calm duck',              'Review with c',         2, 15, 35],
      ['xssxs sxxsx xsxss sxsxx xsxsx sxsxs ssxxs xxssx xsx sxs',              'From s to x',           2, 15, 35],
      ['six oxen on axes sew sox; coax exams so taxis sac boxes',              'Review with x',         2, 15, 35],
      ['jack of care and cash; cats cite chum such that tacks can',            'Left side',             2, 15, 35],
      [',kk,k k,,k, ,k,kk k,k,, ,k,k, k,k,k kk,,k ,,kk, ,k, k,k',              'From k to ,',           2, 15, 35],
      ['kids, like kin, lax fox, and taxi, stick fix, crux hex',               'Review with ,',         2, 15, 35],
      ['.ll.l l..l. .l.ll l.l.. .l.l. l.l.l ll..l ..ll. .l. l.l',              'From l to .',           2, 15, 35],
      ['nil. taxes, ink, and oil... yaks, like oxen, are real.',               'Middle-ring final',     2, 15, 35]]],

    ['Pinkies',
     [['qaaqa aqqaq qaqaa aqaqq qaqaq aqaqa aaqqa qqaaq qaq aqa',              'From a to q',           2, 15, 35],
      ['qi quay aquit and quilts; quill and quad are equal.',                  'Pinkies 2',             2, 15, 35],
      ['zaaza azzaz zazaa azazz zazaz azaza aazza zzaaz zaz aza',              'From a to z',           2, 15, 35],
      ['zag and zig wiz quiz zed and zoe over azure zulu zen',                 'Pinkies 4',             2, 15, 35],
      ['p;;p; ;pp;p p;p;; ;p;pp p;p;p ;p;p; ;;pp; pp;;p p;p ;p;',              'From ; to p',           2, 15, 35],
      ['pole lops lofty pears; please copy cops, pin proper pig',              'Pinkies 6',             2, 15, 35],
      ['/;;/; ;//;/ /;/;; ;/;// /;/;/ ;/;/; ;;//; //;;/ /;/ ;/;',              'From ; to /',           2, 15, 35],
      ["';;'; ;'';' ';';; ;';'' ';';' ;';'; ;;''; '';;' ';' ;';",              "From ; to '",           2, 15, 35],
      ["',' ';' '.' '/' // ; // '/' '.' ';' ','",                              'Right pinky challenge', 2, 15, 35]]],

    ['Repetition 1',
     [['mean mean mean mean mean mean mean mean mean mean mean',               'Repetition',            2, 15, 35],
      ['jeans jeans jeans jeans jeans jeans jeans jeans jeans jeans',          'Repetition',            2, 15, 35],
      ['join; join; join; join; join; join; join; join; join; join;',          'Repetition',            2, 15, 35],
      ['link; link; link; link; link; link; link; link; link; link;',          'Repetition',            2, 15, 35],
      ['reads reads reads reads reads reads reads reads reads reads',          'Repetition',            2, 15, 35],
      ['suit suit suit suit suit suit suit suit suit suit suit',               'Repetition',            2, 15, 35],
      ['change change change change change change change change',              'Repetition',            2, 15, 35],
      ['strong strong strong strong strong strong strong strong',              'Repetition',            2, 15, 35]]],

    ['Repetition 2',
     [['that thing that thing that thing that thing that thing',               'Repetition',            2, 15, 35],
      ['four kids four kids four kids four kids four kids',                    'Repetition',            2, 15, 35],
      ['while out while out while out while out while out while out',          'Repetition',            2, 15, 35],
      ['young ease young ease young ease young ease young ease',               'Repetition',            2, 15, 35],
      ['need food need food need food need food need food',                    'Repetition',            2, 15, 35],
      ['think hard think hard think hard think hard think hard',               'Repetition',            2, 15, 35],
      ['gain loss gain loss gain loss gain loss gain loss gain loss',          'Repetition',            2, 15, 35],
      ['win lose win lose win lose win lose win lose win lose',                'Repetition',            2, 15, 35]]],

    ['Repetition 3',
     [['been gone been gone been gone been gone been gone',                    'Repetition',            2, 15, 35],
      ['link fast link fast link fast link fast link fast',                    'Repetition',            2, 15, 35],
      ['close shop close shop close shop close shop close shop',               'Repetition',            2, 15, 35],
      ['stay late stay late stay late stay late stay late',                    'Repetition',            2, 15, 35],
      ['likes mike likes mike likes mike likes mike likes mike',               'Repetition',            2, 15, 35],
      ['real veal real veal real veal real veal real veal',                    'Repetition',            2, 15, 35],
      ['fief thief fief thief fief thief fief thief fief thief',               'Repetition',            2, 15, 35],
      ['strong will strong will strong will strong will strong will',          'Repetition',            2, 15, 35]]],

    ['Repetition 4',
     [['example example example example example example example',              'Repetition',            2, 15, 35],
      ['children children children children children children',                'Repetition',            2, 15, 35],
      ['together together together together together together',                'Repetition',            2, 15, 35],
      ['thought thought thought thought thought thought thought',              'Repetition',            2, 15, 35],
      ['causation causation causation causation causation causation',          'Repetition',            2, 15, 35],
      ['sentence sentence sentence sentence sentence sentence',                'Repetition',            2, 15, 35],
      ['previous previous previous previous previous previous',                'Repetition',            2, 15, 35],
      ['sensational sensational sensational sensational sensational',          'Repetition',            2, 15, 35]]],

    ['Vowel Focus',
     [['ooiye aiiya ieeyo ioiay eauao aaeoy eoeie yuaao uieyo auoiu',          'Vowels',                2, 15, 35],
      ['aouia eyeuy oyoue eyoeo yyeeu ayioy eueae aoaao oeeey eiooy',          'Vowels',                2, 15, 35],
      ['eyaoe eoyio euuei eyiea yyyai oiuae yeyii yaoia yyuoy euyuy',          'Vowels',                2, 15, 35],
      ['iyaii uyioa aiuea uuoai oiooi uaoou oayua eouyy yeioo aueoo',          'Vowels',                2, 15, 35]]],

    ['Alphabet Tour',
     [['bhoas uaxdg omugi ocznd oaojc jovdd msooq oqsox tvqgs qpyod',          'Alphabet',              2, 15, 35],
      ['tzvfw oncbf fyoio vbrbf phukq wskem qjxoi wnior sjslo ykaqm',          'Alphabet',              2, 15, 35],
      ['ztvtk gcluv ixzst jjlor hlofl hpvnm caheb ympwy srypp swzas',          'Alphabet',              2, 15, 35],
      ['cwfzt mnhjx wbuzv ywgzl nuqcu caoch vqisd jbuzi jekva ljwob',          'Alphabet',              2, 15, 35]]],

    ['Numbers 1',
     [['aq1qa aqa1a 1aqa1 1a1a1 11aa1 a1aa1 1a11a a11a1',                      'From a to 1',           2, 15, 35],
      ['aq2qa aqa2a 2aqa2 2a2a2 22aa2 a2aa2 2a22a a22a2',                      'From a to 2',           2, 15, 35],
      ['sw3ws sws3s 3sws3 3s3s3 33ss3 s3ss3 3s33s s33s3',                      'From s to 3',           2, 15, 35],
      ['de4ed ded4d 4ded4 4d4d4 44dd4 d4dd4 4d44d d44d4',                      'From d to 4',           2, 15, 35],
      ['fr5rf frf5f 5frf5 5f5f5 55ff5 f5ff5 5f55f f55f5',                      'From f to 5',           2, 15, 35],
      ['ft6tf ftf6f 6ftf6 6f6f6 66ff6 f6ff6 6f66f f66f6',                      'From f to 6',           2, 15, 35],
      ['a121 aq2q a21q 21qa aq2a1 1q2q q1a2q q1121 a1q2',                      'Left pinky review',     2, 15, 35],
      ['f565 ft6t f65t 65tf ft6f5 5t6t t5f6t t5565 f5t6',                      'Left index review',     2, 15, 35],
      ['12a3s 65f4a 4d5f 6f4d 4d3s 2a1a a1a2 s3d4 f5f6',                       'Left numbers review',   2, 15, 35]]],

    ['Numbers 2',
     [['ju7uj juj7j 7juj7 7j7j7 77jj7 j7jj7 7j77j j77j7',                      'From j to 7',           2, 15, 35],
      ['ki8ik kik8k 8kik8 8k8k8 88kk8 k8kk8 8k88k k88k8',                      'From k to 8',           2, 15, 35],
      ['lo9ol lol9l 9lol9 9l9l9 99ll9 l9ll9 9l99l l99l9',                      'From l to 9',           2, 15, 35],
      [';p0p; ;p;0; 0;p;0 0;0;0 00;;0 ;0;;0 0;00; ;00;0',                      'From ; to 0',           2, 15, 35],
      [';p-p; ;p;-; -;p;- -;-;- --;;- ;-;;- -;--; ;--;-',                      'From ; to -',           2, 15, 35],
      [';p=p; ;p;=; =;p;= =;=;= ==;;= ;=;;= =;==; ;==;=',                      'From ; to =',           2, 15, 35],
      [';p-=- p;-;=; ;0;-;= ;-0-= ;-;0;= 0;==- -=0; ;0-=',                     'Right pinky review',    2, 15, 35],
      ['l9;0 l9k8 7j k8l9 ;-;= =-;0 l9k8 7j 8k 0; 9l',                         'Right numbers review',  2, 15, 35]]],

    ['Numbers 3',
     [['13 78 31 54 63 23 81 12 91 43 51 74 82 19',                            'Couples mixer',         2, 15, 35],
      ['91 19 53 71 78 49 57 73 18 75 83 51 68 25',                            'Couples mixer',         2, 15, 35],
      ['298 551 130 761 131 568 355 869 421 229 413',                          'Triads mixer',          2, 15, 35],
      ['148 051 617 455 658 748 256 482 109 522 417',                          'Triads mixer',          2, 15, 35],
      ['0901 4596 2901 2164 4736 8129 3223 4204 0538',                         'Quads mixer',           2, 15, 35],
      ['5769 5175 8258 4345 9764 4763 4461 3661 0786',                         'Quads mixer',           2, 15, 35],
      ['steal23 run5 stan8 groi0 1337 5p34k stay100',                          'Alphanumeric',          2, 15, 35],
      ['seven11 rank86 urxvt9 init5 streak574 drop83',                         'Alphanumeric',          2, 15, 35]]],

    ['Using Shift Key',
     [['AsDfG :lKjH AsDfG :lKjH AsDfG :lKjH AsDfG :lKjH',                      'Alternate Shift Keys',  2, 15, 35],
      ['aSdFg ;LkJh aSdFg ;LkJh aSdFg ;LkJh aSdFg ;LkJh',                      'Alternate Shift Keys',  2, 15, 35],
      ['QwErT PoIuY QwErT PoIuY QwErT PoIuY QwErT PoIuY',                      'Alternate Shift Keys',  2, 15, 35],
      ['qWeRt pOiUy qWeRt pOiUy qWeRt pOiUy qWeRt pOiUy',                      'Alternate Shift Keys',  2, 15, 35],
      ['ZxCvB ?.<mN ZxCvB ?.<mN ZxCvB ?.<mN ZxCvB ?.<mN',                      'Alternate Shift Keys',  2, 15, 35],
      ['zXcVb />,Mn zXcVb />,Mn zXcVb />,Mn zXcVb />,Mn',                      'Alternate Shift Keys',  2, 15, 35],
      ['!2#4%^ +-)98& !2#4%^ +-)98& !2#4%^ +-)98&',                            'Alternate Shift Keys',  2, 15, 35]]],

    ['Shift Practice',
     [['A Bad Workman Always Blames His Tools',                                'A Sentence With Shift', 2, 15, 35],
      ['Absence Makes The Heart Grow Stronger',                                'A Sentence With Shift', 2, 15, 35],
      ['A Bird In The Hand Is Worth Two In The Bush',                          'A Sentence With Shift', 2, 15, 35],
      ['A Chain Is ONly As Strong As Its Weakest Link',                        'A Sentence With Shift', 2, 15, 35],
      ['Actions Speak Louder Than Words',                                      'A Sentence With Shift', 2, 15, 35],
      ['A Fool And His Money Are Soon Parted',                                 'A Sentence With Shift', 2, 15, 35],
      ['A Journey Of A Thousand Miles Begins With A Single Step',              'A Sentence With Shift', 2, 15, 35],
      ['Among The Blind The One-Eyed Man Is King',                             'A Sentence With Shift', 2, 15, 35]]],

    ['Symbols 1',
     [['!1!!1 @2@@2 !@12! @!21@ !@! @!@ @@! 1!! 2@@ @1 @2',                    'Left pinky',            2, 15, 35],
      ['+=++= _-__- +_=-+ _+-=_ +_+ _+_ __+ =++ -__ _= _-',                    'Right pinky',           2, 15, 35],
      ['_! _!! +! +!! _=1+2 2+1+2=5 _!=20 5@4=20 4@1=_!',                      'Pinkies combined',      2, 15, 35],
      ['#4 #3 #2 #1 $1 $2 $3 $4 $# $4#3 3#3 4$4 3$3 4#4',                      'Left middle-ring',      2, 15, 35],
      ['%5 ^6 &7 *8 8*8^6 7&7 ^ 5% *8 ^^ 5 &7 8* %5^7',                        'Center symbols',        2, 15, 35],
      ['(9 * 0) + (7 - 7) = 0 (1 - 2) ^ 5 = -1 3 + (-10) = -7',                'Parenthesis',           2, 15, 35]]],

    ['Symbols 2',
     [['[][] [[][] [][]] [][][ [][][ [[][[ [[][] ]][][',                       'Braces',                2, 15, 35],
      ['{}{} {{}{} {}{}} {}{}{ {}{}{ {{}{{ {{}{} }}{}{',                       'Brackets',              2, 15, 35],
      ['\\|\\| \\\\|\\| \\|\\|| \\|\\|\\ \\|\\|\\ \\\\|\\\\ \\\\|\\| ||\\|\\', 'Bar and backslash',     2, 15, 35],
      ['<><> <<><> <><>> <><>< <><>< <<><< <<><> >><><',                       'Angle brackets',        2, 15, 35],
      ['/?/? //?/? /?/?? /?/?/ /?/?/ //?// //?/? ??/?/',                       '/ and ?',               2, 15, 35]]],

    ["Programmer's Dilemma",
     [['<!DOCTYPE html><html><head><title>Hello</title></head></html>',        'HTML',                  2, 15, 35],
      ['p { color: #5500FFBB; text-align: center; cursor: pointer; }',         'CSS',                   2, 15, 35],
      ['window.tick = (x, *xs) => { xs.length <= 1 ? x : xs[0] }',             'Javascript',            2, 15, 35],
      ['def fmx(mx, *tx, &b) tx.map { |t| b[t[0][:y]] || mx.z } end',          'Ruby',                  2, 15, 35],
      ['SELECT COUNT(*) as c from (SELECT DISTINCT name FROM users);',         'SQL',                   2, 15, 35],
      ['(>>) :: IO a -> IO b -> IO b',                                         'Haskell',               2, 15, 35],
      ['Evens = [X || X <- L, X rem 2 == 0],',                                 'Erlang',                2, 15, 35],
      ['void main(int argc, char **argv) { puts("hi %s", *name); }',           'C',                     2, 15, 35]]],

    ['Bonus practice',
     [['A bird in the hand is worth two in the bush.',                         'Bonus Practice 1',      2, 15, 35],
      ['Caught between a rock and a hard place.',                              'Bonus Practice 2',      2, 15, 35],
      ['Closing the barn door after the horse escapes.',                       'Bonus Practice 3',      2, 15, 35],
      ["Don't count your chickens before they hatch.",                         'Bonus Practice 4',      2, 15, 35],
      ["Don't make a mountain out of a molehill.",                             'Bonus Practice 5',      2, 15, 35],
      ['Friends are flowers in the garden of life.',                           'Bonus Practice 6',      2, 15, 35],
      ['The grass is always greener on the other side.',                       'Bonus Practice 7',      2, 15, 35],
      ['Just staying one day ahead of yesterday.',                             'Bonus Practice 8',      2, 15, 35],
      ['Lie down with dogs and wake up with fleas.',                           'Bonus Practice 9',      2, 15, 35],
      ['The sharper the berry, the sweeter the wine.',                         'Bonus Practice 10',     2, 15, 35],
      ['The squeaky wheel gets the grease.',                                   'Bonus Practice 11',     2, 15, 35],
      ['The stronger the breeze the stronger the trees.',                      'Bonus Practice 12',     2, 15, 35],
      ["The way to a man's heart is through his stomach.",                     'Bonus Practice 13',     2, 15, 35],
      ['A weed is no more than a flower in disguise.',                         'Bonus Practice 14',     2, 15, 35],
      ["We'll cross that bridge when we come to it.",                          'Bonus Practice 15',     2, 15, 35],
      ["You can lead a horse to water but you can't make him drink.",          'Bonus Practice 16',     2, 15, 35],
      ["You can't teach an old dog new tricks.",                               'Bonus Practice 17',     2, 15, 35],
      ['All work and no play robs one of some fun in life.',                   'Bonus Practice 18',     2, 15, 35],
      ['Your car is out of date as soon as it is paid for.',                   'Bonus Practice 19',     2, 15, 35]]]]
  end

QWERTY::LESSONS.each_with_index do |(title, exercises), i|
  lesson = Lesson.where(title: title).first || Lesson.create(title: title, position: i)

  lesson.position = i
  lesson.save

  exercises.each_with_index do |(content, title, max_typos, min_wpm, fast_wpm), j|
    exercise = Exercise.where(content: content, lesson_id: lesson.id).first || lesson.add_exercise(content: content, position: j)

    exercise.position = j
    exercise.title = title
    exercise.max_typos = max_typos
    exercise.min_wpm = min_wpm
    exercise.fast_wpm = fast_wpm

    p exercise.save
  end
end
