module QWERTY
  LESSONS = {
    'Home Row Position' => [
      'jkkjk kjkkj jkjjk kkjkj jjkjk jkjkk kjkjj jkjkj kkjkj jjkjk',
      'dffdf fdffd dfddf ffdfd ddfdf dfdff fdfdd dfdfd ffdfd ddfdf',
      'dkfdj jdfkf kjdkf fkjdk fkdkj fkfdj kjdkf dfkfj kfkdj fjkjd',
      'l;;l; ;l;;l l;ll; ;;l;l ll;l; l;l;; ;l;ll l;l;l ;;l;l ll;l;',
      'lfk ;fk djlf kflf ;fkj kj;f dj;;f ;f;lf ;lfkf dljdf ;f;lfkf',
      'assas sassa asaas ssasa aasas asass sasaa asasa ssasa aasas',
      'all add; as ask; sad; fas lad dak; dad fad fall; lass dall;',
      'alas dald fall; dad flak; lass sad; fass; all fall lad; ask',
    ],
    'Index Fingers 1' => [
      'ghhgh hghhg ghggh hhghg gghgh ghghh hghgg ghghg hhghg gghgh',
      'gad has aha; had flag gas; sag ash; gag dash glag half;',
      'tfftf fttft tftff ftftt tftft ftftf ffttf ttfft tft ftf',
      'tft tsk alt gst has hat kat sha ska tad tag that tas tsk',
      'rffrf frrfr rfrff frfrr rfrfr frfrf ffrrf rrffr rfr frf',
      'rag ark rash jarl trash; rash rad lard; drag lar jar',
      'raft; draft arts gats trad task shard hard; hath halt gast',
      'yjjyj jyyjy yjyjj jyjyy yjyjy jyjyj jjyyj yyjjy yjy jyj',
      'ya yald gay yak; yard sty fly kays day kyaf slay; yald lys',
      'ujjuj juuju ujujj jujuu ujuju jujuj jjuuj uujju uju juj',
      'uh husk tau sku; ludd yuk ugh uru juku us; guff usla dull',
      'yurt lady try tardy stray; stalk ya lathy; flay rhytha',
    ],
    'Index Fingers 2' => [
      'vffvf fvvfv vfvff fvfvv vfvfv fvfvf ffvvf vvffv vfv fvf',
      'varus vasty lav var; sylva vat guv; davy vulgar ulvas',
      'bjjbj jbbjb bjbjj jbjbb bjbjb jbjbj jjbbj bbjjb bjb jbj',
      'bad labs dab bald albs; tabs flab bard jab; grub buys garb',
      'njjnj jnnjn njnjj jnjnn njnjn jnjnj jjnnj nnjjn njn jnj',
      'nag and fang; dank hang hank nah; flank land sangh khan',
      'the rags rang vast; bag lard jant ban yards; stud turk',
      'mjjmj jmmjm mjmjj jmjmm mjmjm jmjmj jjmmj mmjjm mjm jmj',
      'mum mut sham rams slam; slum gama smut balm arm mans flam',
      'mad marts smart human; numb ban nag ma and mass lamb rut',
      'vans tan rash fangs; balm must slam sand; arms man salt',
    ],
    'Middle and Ring Fingers 1' => [
      'edded deede ededd dedee edede deded ddeed eedde ede ded',
      'dead ed eats eels; the red deal dreads to age; he feeds',
      'vane envy ends vets vent; use menu but let ten stay fed',
      'wssws swwsw wswss swsww wswsw swsws sswws wwssw wsw sws',
      'sway jaws swat the swan; news was swell when laws saw newt',
      'ikkik kiiki ikikk kikii ikiki kikik kkiik iikki iki kik',
      'kids like kin; kiln kits hike; kale shakes skate unkind',
      'skew vader with likes; liken jade at envy drew swung',
      'ollol loolo ololl loloo ololo lolol llool oollo olo lol',
      'old lords sold bold lots; lads of lore glob local glue',
      'glow alone or redo ideas; sweat on the show for one halo',
    ],
    'Middle and Ring Fingers 2' => [
      'cddcd dccdc cdcdd dcdcc cdcdc dcdcd ddccd ccddc cdc dcd',
      'act coy card aced dice can tacs duct ice ache calm duck',
      'xssxs sxxsx xsxss sxsxx xsxsx sxsxs ssxxs xxssx xsx sxs',
      'six oxen on axes sew sox; coax exams so taxis sac boxes',
      'jack of care and cash; cats cite chum such that tacks can',
      ',kk,k k,,k, ,k,kk k,k,, ,k,k, k,k,k kk,,k ,,kk, ,k, k,k',
      'kids, like kin, lax fox, and taxi, stick fix, crux hex',
      '.ll.l l..l. .l.ll l.l.. .l.l. l.l.l ll..l ..ll. .l. l.l',
      'nil. taxes, ink, and oil... yaks, like oxen, are real.',
    ],
    'Pinkies' => [
      'qaaqa aqqaq qaqaa aqaqq qaqaq aqaqa aaqqa qqaaq qaq aqa',
      'qi quay aquit and quilts; quill and quad are equal.',
      'zaaza azzaz zazaa azazz zazaz azaza aazza zzaaz zaz aza',
      'zag and zig wiz quiz zed and zoe over azure zulu zen',
      'p;;p; ;pp;p p;p;; ;p;pp p;p;p ;p;p; ;;pp; pp;;p p;p ;p;',
      'pole lops lofty pears; please copy cops, pin proper pig',
      '/;;/; ;//;/ /;/;; ;/;// /;/;/ ;/;/; ;;//; //;;/ /;/ ;/;',
      "';;'; ;'';' ';';; ;';'' ';';' ;';'; ;;''; '';;' ';' ;';",
      "',' ';' '.' '/' // ; // '/' '.' ';' ','",
    ],
    'Repetition 1' => [
      'mean mean mean mean mean mean mean mean mean mean mean',
      'jeans jeans jeans jeans jeans jeans jeans jeans jeans jeans',
      'join; join; join; join; join; join; join; join; join; join;',
      'link; link; link; link; link; link; link; link; link; link;',
      'reads reads reads reads reads reads reads reads reads reads',
      'suit suit suit suit suit suit suit suit suit suit suit',
      'change change change change change change change change',
      'strong strong strong strong strong strong strong strong',
    ],
    'Repetition 2' => [
      'that thing that thing that thing that thing that thing',
      'four kids four kids four kids four kids four kids',
      'while out while out while out while out while out while out',
      'young ease young ease young ease young ease young ease',
      'need food need food need food need food need food',
      'think hard think hard think hard think hard think hard',
      'gain loss gain loss gain loss gain loss gain loss gain loss',
      'win lose win lose win lose win lose win lose win lose',
    ],
    'Repetition 3' => [
      'been gone been gone been gone been gone been gone',
      'link fast link fast link fast link fast link fast',
      'close shop close shop close shop close shop close shop',
      'stay late stay late stay late stay late stay late',
      'likes mike likes mike likes mike likes mike likes mike',
      'real veal real veal real veal real veal real veal',
      'fief thief fief thief fief thief fief thief fief thief',
      'strong will strong will strong will strong will strong will',
    ],
    'Repetition 4' => [
      'example example example example example example example',
      'children children children children children children',
      'together together together together together together',
      'thought thought thought thought thought thought thought',
      'causation causation causation causation causation causation',
      'sentence sentence sentence sentence sentence sentence',
      'previous previous previous previous previous previous',
      'sensational sensational sensational sensational sensational',
    ],
    'Vowel Practice' => [
      'ooiye aiiya ieeyo ioiay eauao aaeoy eoeie yuaao uieyo auoiu',
      'aouia eyeuy oyoue eyoeo yyeeu ayioy eueae aoaao oeeey eiooy',
      'eyaoe eoyio euuei eyiea yyyai oiuae yeyii yaoia yyuoy euyuy',
      'iyaii uyioa aiuea uuoai oiooi uaoou oayua eouyy yeioo aueoo',
    ],
    'Alphabet Сryptogram' => [
      'bhoas uaxdg omugi ocznd oaojc jovdd msooq oqsox tvqgs qpyod',
      'tzvfw oncbf fyoio vbrbf phukq wskem qjxoi wnior sjslo ykaqm',
      'ztvtk gcluv ixzst jjlor hlofl hpvnm caheb ympwy srypp swzas',
      'cwfzt mnhjx wbuzv ywgzl nuqcu caoch vqisd jbuzi jekva ljwob',
    ],
    'Numbers 1' => [
      'aq1qa aqa1a 1aqa1 1a1a1 11aa1 a1aa1 1a11a a11a1',
      'aq2qa aqa2a 2aqa2 2a2a2 22aa2 a2aa2 2a22a a22a2',
      'sw3ws sws3s 3sws3 3s3s3 33ss3 s3ss3 3s33s s33s3',
      'de4ed ded4d 4ded4 4d4d4 44dd4 d4dd4 4d44d d44d4',
      'fr5rf frf5f 5frf5 5f5f5 55ff5 f5ff5 5f55f f55f5',
      'ft6tf ftf6f 6ftf6 6f6f6 66ff6 f6ff6 6f66f f66f6',
      'a121 aq2q a21q 21qa aq2a1 1q2q q1a2q q1121 a1q2',
      'f565 ft6t f65t 65tf ft6f5 5t6t t5f6t t5565 f5t6',
      '12a3s 65f4a 4d5f 6f4d 4d3s 2a1a a1a2 s3d4 f5f6',
    ],
    'Numbers 2' => [
      'ju7uj juj7j 7juj7 7j7j7 77jj7 j7jj7 7j77j j77j7',
      'ki8ik kik8k 8kik8 8k8k8 88kk8 k8kk8 8k88k k88k8',
      'lo9ol lol9l 9lol9 9l9l9 99ll9 l9ll9 9l99l l99l9',
      ';p0p; ;p;0; 0;p;0 0;0;0 00;;0 ;0;;0 0;00; ;00;0',
      ';p-p; ;p;-; -;p;- -;-;- --;;- ;-;;- -;--; ;--;-',
      ';p=p; ;p;=; =;p;= =;=;= ==;;= ;=;;= =;==; ;==;=',
      ';p-=- p;-;=; ;0;-;= ;-0-= ;-;0;= 0;==- -=0; ;0-=',
      'l9;0 l9k8 7j k8l9 ;-;= =-;0 l9k8 7j 8k 0; 9l',
    ],
    'Using Shift Key' => [
      'AsDfG :lKjH AsDfG :lKjH AsDfG :lKjH AsDfG :lKjH',
      'aSdFg ;LkJh aSdFg ;LkJh aSdFg ;LkJh aSdFg ;LkJh',
      'QwErT PoIuY QwErT PoIuY QwErT PoIuY QwErT PoIuY',
      'qWeRt pOiUy qWeRt pOiUy qWeRt pOiUy qWeRt pOiUy',
      'ZxCvB ?.<mN ZxCvB ?.<mN ZxCvB ?.<mN ZxCvB ?.<mN',
      'zXcVb ?.<Mn zXcVb ?.<Mn zXcVb ?.<Mn zXcVb ?.<Mn',
      '!2#4%^ +-)98& !2#4%^ +-)98& !2#4%^ +-)98&',
    ],
    'Bonus practice' => [
      'A bird in the hand is worth two in the bush.',
      'Caught between a rock and a hard place.',
      'Closing the barn door after the horse escapes.',
      "Don't count your chickens before they hatch.",
      "Don't make a mountain out of a molehill.",
      'Friends are flowers in the garden of life.',
      'The grass is always greener on the other side.',
      'Just staying one day ahead of yesterday.',
      'Lie down with dogs and wake up with fleas.',
      'The sharper the berry, the sweeter the wine.',
      'The squeaky wheel gets the grease.',
      'The stronger the breeze the stronger the trees.',
      "The way to a man's heart is through his stomach.",
      'A weed is no more than a flower in disguise.',
      "We'll cross that bridge when we come to it.",
      "You can lead a horse to water but you can't make him drink.",
      "You can't teach an old dog new tricks.",
      'All work and no play robs one of some fun in life.',
      'Your car is out of date as soon as it is paid for.',
    ]
  }
end

if Lesson.all.none?
  QWERTY::LESSONS.each_with_index do |(title, exercises), i|
    lesson = Lesson.create(title: title, position: i)
    exercises.each_with_index do |content, j|
      lesson.add_exercise(content: content, position: j)
    end
  end
end
